const express = require('express');
const cors = require('cors');
const dotenv = require('dotenv');
const { createProxyMiddleware } = require('http-proxy-middleware');
const rateLimit = require('express-rate-limit');

dotenv.config();

const app = express();
const PORT = process.env.PORT || 3001;

// Rate Limiting: 100 requests per 15 minutes
const limiter = rateLimit({
	windowMs: 15 * 60 * 1000, 
	max: 100, 
	standardHeaders: true, 
	legacyHeaders: false, 
    message: { status: 'error', message: 'Too many requests, please try again later.' }
});

app.use(cors());
app.use(limiter); 

// Stricter Rate Limiting for AI endpoints (20 requests per 15 minutes)
const aiLimiter = rateLimit({
    windowMs: 15 * 60 * 1000,
    max: 20,
    standardHeaders: true,
    legacyHeaders: false,
    message: { status: 'error', message: 'AI generation limit reached. Please try again in 15 minutes.' }
});

// Apply stricter limit to high-cost AI routes
app.use('/api/v1/query', aiLimiter);
app.use('/api/v1/summarize', aiLimiter);
app.use('/api/v1/draft', aiLimiter);
app.use('/api/v1/compare', aiLimiter);

// Health check
app.get('/health', (req, res) => {
  res.json({ status: 'ok', service: 'API Gateway' });
});

// Proxy Configuration for RAG Service
let RAG_SERVICE_URL = process.env.RAG_SERVICE_URL || 'http://localhost:8000';

// Ensure protocol exists for http-proxy-middleware
if (!RAG_SERVICE_URL.startsWith('http://') && !RAG_SERVICE_URL.startsWith('https://')) {
    if (!RAG_SERVICE_URL.includes(':')) {
        RAG_SERVICE_URL = `http://${RAG_SERVICE_URL}:8000`;
    } else {
        RAG_SERVICE_URL = `http://${RAG_SERVICE_URL}`;
    }
}

const path = require('path');

// Sarvam AI Text-to-Speech Human Voice Route
app.post('/api/v1/tts', express.json({ limit: '2mb' }), async (req, res) => {
    const { text, language = 'en' } = req.body;
    const sarvamKey = process.env.SARVAM_API_KEY;

    if (!sarvamKey) {
        return res.status(503).json({ error: 'SARVAM_API_KEY is not configured on server' });
    }

    if (!text || typeof text !== 'string') {
        return res.status(400).json({ error: 'Valid text string is required' });
    }

    try {
        // Clean markdown, links, asterisks
        const clean = text
            .replace(/https?:\/\/\S+/gi, '')
            .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
            .replace(/[*#_`>~|]/g, ' ')
            .replace(/\s+/g, ' ')
            .trim();

        if (!clean) {
            return res.status(400).json({ error: 'No readable text content' });
        }

        // Split text into chunks of <= 450 characters (Sarvam limit is 500 per string)
        const sentences = clean.match(/[^.!?।\n]+[.!?।\n]+/g) || [clean];
        const chunks = [];
        let current = "";

        for (const s of sentences) {
            if ((current + " " + s).trim().length <= 450) {
                current = (current + " " + s).trim();
            } else {
                if (current) chunks.push(current);
                if (s.length > 450) {
                    const words = s.split(' ');
                    let sub = "";
                    for (const w of words) {
                        if ((sub + " " + w).trim().length <= 450) {
                            sub = (sub + " " + w).trim();
                        } else {
                            if (sub) chunks.push(sub);
                            sub = w;
                        }
                    }
                    if (sub) current = sub;
                } else {
                    current = s.trim();
                }
            }
            if (chunks.length >= 4) break; // Limit to ~1800 characters to keep audio responsive
        }
        if (current && chunks.length < 4) chunks.push(current);

        const isHindi = language === 'hi' || /[\u0900-\u097F]/.test(clean);
        const targetLang = isHindi ? 'hi-IN' : 'en-IN';

        const sarvamRes = await fetch('https://api.sarvam.ai/text-to-speech', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'api-subscription-key': sarvamKey
            },
            body: JSON.stringify({
                inputs: chunks.length > 0 ? chunks : [clean.slice(0, 450)],
                target_language_code: targetLang,
                speaker: 'kavya',
                model: 'bulbul:v3'
            })
        });

        if (!sarvamRes.ok) {
            const errText = await sarvamRes.text();
            console.error('[Sarvam TTS Error]:', sarvamRes.status, errText);
            return res.status(sarvamRes.status).json({ error: 'Sarvam API Error', detail: errText });
        }

        const data = await sarvamRes.json();
        if (data.audios && data.audios.length > 0) {
            return res.json({ audio: data.audios[0], format: 'wav', speaker: 'kavya' });
        } else {
            return res.status(500).json({ error: 'No audio generated by Sarvam' });
        }
    } catch (err) {
        console.error('[TTS Route Error]:', err);
        return res.status(500).json({ error: err.message });
    }
});

// API Routes Proxy
app.use('/api/v1', createProxyMiddleware({ 
    target: RAG_SERVICE_URL, 
    changeOrigin: true,
    pathRewrite: {
        '^/api/v1': '', // Remove /api/v1 prefix when forwarding to RAG service
    },
    onProxyReq: (proxyReq, req, res) => {
        console.log(`[Gateway] Forwarding ${req.method} request to: ${proxyReq.path}`);
    },
    onError: (err, req, res) => {
        console.error(`[Gateway] Proxy connection error to ${RAG_SERVICE_URL}:`, err.message);
        if (!res.headersSent) {
            res.status(502).json({
                status: 'error',
                message: 'Unable to connect to LegalAi RAG service. Service may still be spinning up.',
                detail: err.message
            });
        }
    },
    proxyTimeout: 300000,
    timeout: 300000
}));

// Serve Static Files from Frontend Dist (Production)
const DIST_PATH = path.join(__dirname, '../dist');
app.use(express.static(DIST_PATH));

// Catch-all route for SPA
app.get('*', (req, res) => {
    // Check if the request is not for an API route
    if (!req.path.startsWith('/api/v1')) {
        res.sendFile(path.join(DIST_PATH, 'index.html'));
    }
});

app.listen(PORT, () => {
  console.log(`API Gateway running on port ${PORT}`);
  console.log(`Proxying /api/v1 -> ${RAG_SERVICE_URL}`);
});
